#!/bin/sh
set -eo pipefail

host="$(hostname -i || echo '127.0.0.1')"
err="can't connect to remote host"

if ping="$(wget "$host:7001" 2>&1 | grep -c "$err")" && [ "$ping" != '0' ]; then
	exit 1
fi

if ping="$(wget "$host:8090" 2>&1 | grep -c "$err")" && [ "$ping" != '0' ]; then
	exit 1
fi

if ping="$(wget "$host:1935" 2>&1 | grep -c "$err")" && [ "$ping" != '0' ]; then
	exit 1
fi

exit 0